### ISSUE TITLE
how to reduce .so dependencies?

### ISSUE THREAD

**Issue by cailiang9** [tbenthompson/cppimport#16]
for example in the cpp head I add a lot lib dependences:
cfg['libraries'] = 'opencv_core opencv_imgproc opencv_imgcodecs opencv_video opencv_videoio opencv_objdetect m z'.split()

but actually not all of them are used.
ldd cpy.so will output:
	libopencv_core.so.3.2 => /conda/lib/libopencv_core.so.3.2 (0x00007fc2879b1000)
	libopencv_imgproc.so.3.2 => /conda/lib/libopencv_imgproc.so.3.2 (0x00007fc286208000)
	libopencv_imgcodecs.so.3.2 => /conda/lib/libopencv_imgcodecs.so.3.2 (0x00007fc285dcb000)
	libopencv_video.so.3.2 => /conda/lib/libopencv_video.so.3.2 (0x00007fc285a56000)
	libopencv_videoio.so.3.2 => /conda/lib/libopencv_videoio.so.3.2 (0x00007fc285825000)
	libopencv_objdetect.so.3.2 => /conda/lib/libopencv_objdetect.so.3.2 (0x00007fc2855c8000)

But if I compile with g++ in Makefile. The unused library dependencies are removed automatically.
So how can I enable this in cppimport cfg?

I did tried flags -flto -Os from https://stackoverflow.com/questions/31354641/c-reduce-library-size-by-excluding-unnecessary-functions-programmatically . But it doesn't work.

**Comment by tbenthompson** [comment]
cppimport is not a compiler. Underneath, it uses whatever your python default compiler is. Per the distutils default, it also compiles including the compiler flags that were used to compile your python installation binaries. You can see exactly what compilation commands are being run by calling cppimport.set_quiet(False).
