### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by adam-urbanczyk** [tbenthompson/cppimport#19]
Not a real issue, but I guess you'll be interested in the following:

cppimport seems to be working with Python 3.6 and Visual C++ 2015 Build Tools on Windows out of the box.

**Comment by tbenthompson** [comment]
Great. I edited the readme to reflect this. 

Thanks for letting me know!!!

**Comment by BSVogler** [comment]
> I don't know if cppimport works on Windows. If you're on Windows, try it out and I'll happily accept a pull request for any issues that you fix. I have reports that cppimport works on Windows with Python 3.6 and Visual C++ 2015 Build Tools.

It still says this. Came here because looking for the answer wether it runs on windows.

**Comment by tbenthompson** [comment]
Thanks. I updated the readme to reflect new information about cppimport on Windows. Try it out and let me know if you have issues!
