### ISSUE TITLE
Support standard kwargs to Extension

### ISSUE THREAD

**Issue by anntzer** [tbenthompson/cppimport#20]
Currently, cppimport seems to rename certain keyword in cfg before passing them to setuptools.Extension, e.g. "compiler_args" -> "extra_compile_args" (https://github.com/tbenthompson/cppimport/blob/c187236363b8ad7df3b5be5186e204d03c965db6/cppimport/build_module.py#L124; I tried using extra_compile_args, with no success).  It would be appreciated if standard kwargs to setuptools.Extension were supported (instead?).  While the standard kwargs may or may not be very well named, they are, well, standard, and I think it's clearer to keep using them rather than introducing your own set of synonyms.

Thanks for the greatly useful project!

**Comment by tbenthompson** [comment]
Thanks for pointing out the inconsistency. I'm thinking that both for backwards compatibility and because I like it better, it'd be nice to support both options. 

Want to submit a pull request? If not, I'm happy to do it!

**Comment by anntzer** [comment]
You get to do it :-)
