### ISSUE TITLE
How specify compiler?

### ISSUE THREAD

**Issue by habemus-papadum** [tbenthompson/cppimport#24]
How would I specify the path to compiler I would like to use?
Is the proper solution to set the CC env var prior to importing?
thanks!

**Comment by tbenthompson** [comment]
It just uses whatever compiler distutils is set up to use. The top 3 answers here (https://stackoverflow.com/questions/16737260/how-to-tell-distutils-to-use-gcc) have several ways of setting that:
-- export CC=...
-- inside python: import os; os.environ['CC'] = ...
-- set the value in the appropriate distutils.cfg file
