### ISSUE TITLE
Update pybind11 example to use PYBIND11_MODULE

### ISSUE THREAD

**Issue by anntzer** [tbenthompson/cppimport#26]
Since pybind11 2.2, PYBIND11_PLUGIN is deprecated in favor of PYBIND11_MODULE (http://pybind11.readthedocs.io/en/stable/changelog.html#v2-2-0-august-31-2017).  The example at the top of the README could be updated to use the latter.

**Comment by tbenthompson** [comment]
Thanks! I updated this in the example and in the tests.

**Comment by anntzer** [comment]
Any chance for a new release including this fix?  Thanks!
(Right now I can just install for the git repo, it's just a matter of convenience.)

**Comment by tbenthompson** [comment]
Done! Good suggestion.

**Comment by anntzer** [comment]
Thanks!
