### ISSUE TITLE
compilation errors are reported at the wrong line

### ISSUE THREAD

**Issue by anntzer** [tbenthompson/cppimport#29]
Right now, compilation errors are not reported at the "right" line of the source file as they actually refer to the line numbering of the "rendered" source.  However, if the Mako templating part is indeed kept in comments and only used to set up the `cfg` dictionary, then you could choose to not copy the rendered source, but just use the original one (and just run Mako for side-effect purposes only).  This would also allow getting rid of the .rendered. files, though that's only a minor benefit.

Would you consider making such a change?

**Comment by tbenthompson** [comment]
This is really interesting. It's always been something that frustrated me too, but I end up using the Mako templating a lot in the actual code, not just for configuration, so it's never been a fixable problem for most of my use cases. But, like you say, if a user is using the Mako block just for the side effects and configuration of the compilation process, then it's an easy fix! 

I'm pretty sure I want to keep the current behavior as the default, but maybe it would be worth adding this as an option. I'd actually tend a slightly different direction and have an interface for specifying all the compilation flags outside of the source itself: essentially separate the Mako side-effect step from the compilation step. 

What do you think of that?

**Comment by anntzer** [comment]
For my use case, putting flags as part of the file is pretty close to the whole point of cppimport; if I'm going to split things over multiple files I may as well go the whole route of setup.py (I have a template for that anyways so it's only mildly a pain to set up).

I may just end up writing my own version of the whole thing to see how this goes... (I'll let you know if this goes anywhere.)

**Comment by tbenthompson** [comment]
Cool! That's really useful feedback. I'm super busy lately but I'll add an option for this soon. What I'm imagining is another `cfg` entry: maybe `use_original_source`?

**Comment by anntzer** [comment]
Sure, sounds reasonable.
