### ISSUE TITLE
specify compile options?

### ISSUE THREAD

**Issue by nbecker** [tbenthompson/cppimport#3]
Is there a way to specify compile options?

I need to:
* specify include path for pybind11
* specify optimization options

**Comment by tbenthompson** [comment]
The pybind11 include path is already added to the compile options.

Concerning more general compile options, there will be a way to do this. If you want to take a look, there are some ideas in the "master" branch. At the moment, the compiler flags are the setuptools/distutils default. If the compilation is failing with "<pybind11/pybind11.h> not found", you might be running into this bug: https://github.com/pypa/pip/issues/3696
