### ISSUE TITLE
Make setup_pybind11 include -fvisibility=hidden in extra_compile_args

### ISSUE THREAD

**Issue by anntzer** [tbenthompson/cppimport#30]
Without that flag, one gets warnings per https://pybind11.readthedocs.io/en/stable/faq.html#someclass-declared-with-greater-visibility-than-the-type-of-its-field-someclass-member-wattributes.

It's probably just a matter of adding it after `-std=c++11` in https://github.com/tbenthompson/cppimport/blob/a2f85f355897badc1a94042802da916820e0657e/cppimport/templating.py#L25 (but before `+ cfg['compiler_args']` to allow a user to overwrite that if they really, really want to).

**Comment by tbenthompson** [comment]
I've actually had a use case with cppimport in the past where I didn't want to have `-fvisibility=hidden` because I was sharing symbols between two libraries. Since this is just producing a warning, I'm inclined to leave it to users to add the flag. Does that sound reasonable?

**Comment by anntzer** [comment]
But for that case you could just add `-fvisibility=default` to the compiler_args in your own config?  I'd think the default config for pybind11 (as provided by setup_pybind11) should follow pybind11's recommendations, which is to use hidden visibility.
OTOH it's not the end of the world if you decide against it, it's just an annoyance.

**Comment by tbenthompson** [comment]
Good point! I agree. Thanks for the suggestion.

**Comment by tbenthompson** [comment]
Closed by ac10ff73b5ed2b3e70ec6850c059296e40b353b7

**Comment by anntzer** [comment]
Uh, I think you got the commit wrong: you added `-fvsisibility=default` to setup_pybind11, but I was suggesting to add `-fvisibility=hidden` to setup_pybind11 and then in your project which does need default visibility, add `-fvisibility=default`.

**Comment by tbenthompson** [comment]
Yeah. I noticed and fixed it, but you caught it in the 90 seconds in between commit 1 and 2... You're super on top of things!
