### ISSUE TITLE
Could dependencies or sources be matched via wildcards?

### ISSUE THREAD

**Issue by roastduck** [tbenthompson/cppimport#32]
It would be better to specify source files like

```
cfg['dependencies'] = ['src/*.cpp']
```

**Comment by tbenthompson** [comment]
I don't think this needs to be a `cppimport` feature. You can just use the glob module:

```
import glob
cfg['dependencies'] += glob.glob('src/*.cpp')
```

**Comment by roastduck** [comment]
I encountered a path issue using glob. If the file structure is like:

```
A/__init__.py
A/x.cpp
A/B/y.cpp
```

If importing `A/x.cpp` from the root directory with `import A.x`, the preprocessor will use the root directory as the working directory, therefore in `A/x.cpp` I will have to write as `cfg['dependencies'] += glob.glob('A/B/*.cpp')`. But then the compiler will try to find `y.cpp` in `A/A/B`, where it doesn't exist.

**Comment by tbenthompson** [comment]
You can either use absolute paths, or split the paths returned by glob to remove the first folder name from them.
