### ISSUE TITLE
How to import a cpp file from another dir?

### ISSUE THREAD

**Issue by vmgustavo** [tbenthompson/cppimport#34]
The function (`somecode = cppimport.imp("somecode")`) can't find the cpp file if the file is not in the working dir.
The function (`cppimport.imp_from_filepath`) returns errors for all the arguments I tried (I could not find documentation).

What is the method for importing cpp files from directories diferrent from the working dir?

**Comment by tbenthompson** [comment]
`cppimport.imp` should look through the same directories as any `import` command: your python path. You can add a directory to your python path:
```
import sys
sys.path.append '/path/to/your/python/module')
```

`cppimport.imp_from_filepath` is not public API and should not be used.

Does that help?

**Comment by vmgustavo** [comment]
That helps a lot,  but it still doesn't work.

I tried this:
```
sys.path.extend('src/')
clib = cppimport.imp('clib')
```

It returned this: `ImportError: Couldn't find a file matching the module name: clib  (note: opt_in = False)`

**Comment by vmgustavo** [comment]
It was the `extend` on the sys path. It works now. Thank you

**Comment by tbenthompson** [comment]
Great!
