### ISSUE TITLE
setup_pybind11(cfg) in /* */ or not?

### ISSUE THREAD

**Issue by dickreuter** [tbenthompson/cppimport#37]
I'm having issues with 

```
/*
<%
setup_pybind11(cfg)
%>
*/
```

It appears that when I put it in /* */ as described in the documentation, then it has no effect when the cpp file is imported from python. However, it all works fine from python when I don't use the /* */, but then I can't run it anymore from visual studio. Any suggestions what I can do? Why do I have to remove the /* */ to work it correctly from python?

**Comment by tbenthompson** [comment]
I see this got closed. Is there still something I could help with? I'm not sure I understand the original question. Maybe you could give a more complete example of what isn't working for you?

**Comment by dickreuter** [comment]
thanks, this is all ok. However I was unable to solve this problem: It's not clear in the documentation how I can import cpp project with multiple files
https://stackoverflow.com/questions/59231288/import-multiple-cpp-files-with-pybind11-and-cppimport

**Comment by tbenthompson** [comment]
Great question. There is some very very brief documentation for that: https://github.com/tbenthompson/cppimport#i-want-multiple-source-files-for-one-extension

But, to expand on that a little, in the example for your stackoverflow post, you'll want to change the header of `main.cpp` to look like:
```
/*
<%
setup_pybind11(cfg)
cfg['sources'] = ['other.cpp']
%>
*/
```

**Comment by dickreuter** [comment]
great, that works! thanks!
