### ISSUE TITLE
Indentation error in macosx

### ISSUE THREAD

**Issue by amrit-poudel** [tbenthompson/cppimport#40]
I keep getting the following indentation error in macosx 10.15. However, the same code runs fine in linux.

<%
cfg['compiler_args'] = ['-std=c++11']
cfg['include_dirs'] = ['/Users/amritpoudel/Desktop/HPC_LIB/HOMEBREW/opt/eigen/include/eigen3', '/Users/amritpoudel/Desktop/HPC_LIB/HOMEBREW/include/python3.7m',
'/Users/amritpoudel/Desktop/HPC_LIB/HOMEBREW/opt/python3/Frameworks/Python.framework/Versions/3.7/include/python3.7m']
cfg['libraries'] = ['/Users/amritpoudel/Desktop/HPC_LIB/HOMEBREW/opt/python3/Frameworks/Python.framework/Versions/3.7/lib']
setup_pybind11(cfg)
%>

#############################################

return compile(expr, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
    cfg['include_dirs'] = ['/Users/amritpoudel/Desktop/HPC_LIB/HOMEBREW/opt/eigen/include/eigen3',
    ^
IndentationError: unexpected indent

I don't quite understand why it complains in macosx. The same copy-pasted code runs fine in linux machine, so indentation shouldn't be an issue.

**Comment by tbenthompson** [comment]
I haven't seen this issue before. I also don't have access to a Mac to test. Are you sure you aren't mixing tabs and spaces in the same file?

**Comment by amrit-poudel** [comment]
<%
cfg['compiler_args'] = ['-std=c++11']
cfg['include_dirs'] = ['/Users/amritpoudel/Desktop/HPC_LIB/HOMEBREW/opt/eigen/include/eigen3', '/Users/amritpoudel/Desktop/HPC_LIB/HOMEBREW/include/python3.7m',
'/Users/amritpoudel/Desktop/HPC_LIB/HOMEBREW/opt/python3/Frameworks/Python.framework/Versions/3.7/include/python3.7m']
cfg['libraries'] = ['/Users/amritpoudel/Desktop/HPC_LIB/HOMEBREW/opt/python3/Frameworks/Python.framework/Versions/3.7/lib']
setup_pybind11(cfg)
%>

There is no indentation in the above piece of code. The same exact code runs fine on linux. However, on macosx, I keep getting the error I reported in my previous email. I think this is a bug in cppimport/mako in macosx.

**Comment by tbenthompson** [comment]
Thanks. Could you share a full file example that fails for you on Mac?

**Comment by amrit-poudel** [comment]
First of all: 
/*
<%
cfg[] = []
setup_pybind11(cfg)
%>
*/


vs 

<%
cfg[] = []
setup_pybind11(cfg)
%>

which one is the correct syntax?

Second:
cppimport is using clang to compile the code in macosx by default. I am not sure if that is causing issue here. How can I force cppimport to use gcc compiler before compiling the c++ code?

**Comment by tbenthompson** [comment]
Both of them are acceptable syntax. The mako templates will be processed/removed from the code before it is compiled. The version where the mako template is inside a block comment is useful for allowing the code to also be compiled with other tools besides cppimport. It's also used to indicate that a C++ module can be loaded via the import hook (https://github.com/tbenthompson/cppimport/#i-want-things-to-be-even-easier-python-import-hook). 

As far as changing the compiler, that's not handled by cppimport, but by distutils. I think setting the `CC` environment variable should let you set your compiler: https://stackoverflow.com/questions/16737260/how-to-tell-distutils-to-use-gcc

**Comment by amrit-poudel** [comment]
I am unable to reproduce my above error after I cleaned  up the folder and moved my test file one by one, without making any change in my actual test code at all.

The above code works fine on macosx as well. I am able to control the type of the compiler, compiler flags (via distutils) as well and compile and run my code.

Thanks for a very useful piece of software. Saves a lot of time!

**Comment by tbenthompson** [comment]
Glad it's working now!
