### ISSUE TITLE
Error SystemExit

### ISSUE THREAD

**Issue by alvaroor97** [tbenthompson/cppimport#41]
Firstly, congratulations! This python module is very useful. My problem is:

After execute this code:
import cppimport
func = cppimport.imp("file_name")
func

This error appears:
SystemExit: error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

I think that the problem is that file_name.cpp creates a file.exe and then it runs. Can it be resolved? I need run file.exe to update the data I need.

Thanks

**Comment by tbenthompson** [comment]
I don't think I have enough info here to help you. Could you paste more output and explain a bit more about what you're doing?
