### ISSUE TITLE
Import header-only implementations.

### ISSUE THREAD

**Issue by kbruegge** [tbenthompson/cppimport#42]
Hello,

thanks for creating this super helpful project. :+1:. I was wondering whether its possible to import header-only implementations. 
I tried:
```
import cppimport
cppimport.config.file_exts.append(".h")
```
But I get 
```
error: unknown file type '.h' (from '<path-on-my-system>/.rendered.ema.h')
```

Thanks for the great work 👍

**Comment by tbenthompson** [comment]
Interesting. Thanks for the bug report. I'll look into this and see if there's an easy fix and whether it would make sense to support. My guess is that distutil's compilation mechanisms are not set up to recognize the `.h` file. 

An easy workaround would be to just have an empty `.cpp` file: 
```
#include "ema.h"
```
