### ISSUE TITLE
Error: No such file or directory: 'VERSION'

### ISSUE THREAD

**Issue by pdavis39** [tbenthompson/cppimport#46]
When I try to install cppimport via pip on multiple machine I receive the same error message.  

The error message is: FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'

The Python versions are 3.6.9 and 3.7.0

Thanks

Paul

**Comment by tbenthompson** [comment]
Thank you very much for reporting this! I'm fixing it right now.

**Comment by tbenthompson** [comment]
This should be fixed now. You might need to add `--no-cache` to the pip install command to make sure it doesn't use a locally cached copy instead of the new version on PyPI. Can you let me know if that works for you?

**Comment by pdavis39** [comment]
thanks for the prompt fix, and yes it works

**Comment by tbenthompson** [comment]
Great!
