### ISSUE TITLE
Added Carriage Return Characters in Rendered Output on Windows

### ISSUE THREAD

**Issue by DanSzaboStoneAge** [tbenthompson/cppimport#49]
I was following through the example in the readme, using Python 3.9, Windows 10, and MSVC2019.  FWIW, I had to add a `cfg['compiler_args'] = []` to the mako section to keep the compiler from barking at me.  Once everything was working, I noticed that the compiler was giving me a warning that the source file was MacOS/Linux formatted.  I opened the rendered cpp file and sure enough, every CR/LF was replaced with a CR/CR/LF.

I was able to fix the issue on my machine by adding the `newline=''` argument to the `open()` call on line 62 of templating.py.

I figure that since the `buf` object already has newlines in it, additional formatting is probably not required.  Cheers.

**Comment by tbenthompson** [comment]
Thanks for this! I've made the change to the main branch. It'll be in the next release. Until then, you can always install from github if you prefer.

Much appreciated.
