### ISSUE TITLE
Not working on cpp file that uses #include with angualar brackets

### ISSUE THREAD

**Issue by siv2r** [tbenthompson/cppimport#60]
I have the following source cpp file. Creating a binding for this file with cppimport work perfectedly.
```cpp
#include "../build/example2.h"

int add(int, int);

int add(int i, int j) {
    int a = MAX_VAL;
    return i*j + a;
}
```

if I use `#include <build/example2.h>` instead of `#include "../build/example2.h"` in the above program. I get the following error.
```bash
fatal error: /build/example2.h: No such file or directory
    1 | #include </build/example2.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-Linux-gnu-gcc' failed with exit status 1
```
NOTE: the `binding.cpp` for this file using cppimort is present in a different directory.

I think cppimport fails if the source file includes angular brackets (ex: `#include<build/example.h>`) instead of double-quotes. Is there a way to make `cppimport` work for angular brackets too?

**Comment by tbenthompson** [comment]
Thanks for the issue! I'm having trouble replicating the problem you're having. I see you shared the source for the case with quotation marks where it *is* working. Could you also share the full source for the case that is not working just in case there's a detail that I have different from you?

**Comment by siv2r** [comment]
I have set up a sample repository explaining this issue in detail with an example code. You can find it [here](https://github.com/siv2r/cppimport-example).
I hope it makes things clear!

**Comment by tbenthompson** [comment]
I'm getting a failure regardless of whether quotation marks or brackets are used.
```
(cppimport) ➜  cppimport-example git:(master) ✗ python main.py                  
/home/tbent/cppimport-example/bindings/../src/example.cpp:1:10: fatal error: src/max_val.h: No such file or directory
    1 | #include <src/max_val.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
(cppimport) ➜  cppimport-example git:(master) ✗ sed -i 's/</"/g' src/example.cpp
(cppimport) ➜  cppimport-example git:(master) ✗ sed -i 's/>/"/g' src/example.cpp
(cppimport) ➜  cppimport-example git:(master) ✗ python main.py                  
/home/tbent/cppimport-example/bindings/../src/example.cpp:1:10: fatal error: src/max_val.h: No such file or directory
    1 | #include "src/max_val.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
```

If for some reason, it is still working for you when you use quotation marks, that's surprising. I wouldn't expect this to work without adding the root of your repo to your include path. I think this is just a misunderstanding of include paths. Backing up and just compiling with g++ directly, I get the same include error. But, when I add the base directory of your repo to the include directories with `-I.`, there's no problem: 
```
(cppimport) ➜  cppimport-example git:(master) ✗ g++ -c src/example.cpp 
src/example.cpp:1:10: fatal error: src/max_val.h: No such file or directory
    1 | #include <src/max_val.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
(cppimport) ➜  cppimport-example git:(master) ✗ g++ -c -I. src/example.cpp
(cppimport) ➜  cppimport-example git:(master) ✗ 
```

[See here for how to do this in cppimport](https://github.com/tbenthompson/cppimport#how-can-i-set-compiler-or-linker-args)

**Comment by siv2r** [comment]
> /home/tbent/cppimport-example/bindings/../src/example.cpp:1:10: fatal error: src/max_val.h: No such file or directory
>     1 | #include "src/max_val.h"

Instead of this, If you write `#include "./max_val.h"`. You will get an output value of `90`.

> I think this is just a misunderstanding of include paths.
Ahh, I see. Thanks for the clarification!

So, How to use `cppimport` in this case? Is the way to tell `cppimport` to include the root folder while building the bindings?
I did try using the `cfg['include_dirs']` option, but it didn't work.
