### ISSUE TITLE
PyPi source contains binaries (.so/.pyc files) in test folder

### ISSUE THREAD

**Issue by ItzSwirlz** [tbenthompson/cppimport#64]
It seems what is uploaded to PyPi is 'after' the build, and it leaves behind some binaries. PyPi should only contain the libraries right? I don't think there's a need for the binaries to be part of the source

**Comment by tbenthompson** [comment]
Yes, this is definitely incorrect in the PyPi build. I'll get this fixed. The issue is this line: https://github.com/tbenthompson/cppimport/blob/a3ac34b575cf586fa762adef7dce1f6c10abcc86/MANIFEST.in#L3
It should be edited to only match *.h, *.cpp, *.c, *.py.

Thanks for pointing this out.

**Comment by ItzSwirlz** [comment]
Thanks, Debian packaging (lintian)  was complaining about it :)

**Comment by ItzSwirlz** [comment]
Thanks, Debian packaging (lintian)  was complaining about it :)
