### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by tbenthompson** [tbenthompson/cppimport#70]
Currently, it's a silly manual process documented here: https://github.com/tbenthompson/cppimport/blob/stable/release

**Comment by mityax** [comment]
I found this to be configurable within about 2 mins from my mobile using the "Publish a Python Package" action by GithubActions. I can only recommend doing this, since it was so straight forward. You need to do it however because of the PyPi access token :)

**Comment by tbenthompson** [comment]
This works now using the pypi github action. See `build-and-publish` in https://github.com/tbenthompson/cppimport/blob/stable/.github/workflows/test.yml

I've also updated the the release instructions in the file from the original post here.
