### ISSUE TITLE
Please add a __version__ attribute to the module

### ISSUE THREAD

**Issue by bjornfor** [tbenthompson/cppimport#77]
It's a very common attribute, which I missed today.

https://peps.python.org/pep-0396/
https://peps.python.org/pep-0008/

**Comment by bjornfor** [comment]
As a workaround I did `pip show cppimport | awk '/Version:/{print $2}`.

**Comment by tbenthompson** [comment]
Yeah, reasonable request! I made a PR (https://github.com/tbenthompson/cppimport/pull/78). Once I confirm that everything is good to go, I'll push a release. 

For future reference, in Python 3.8+, you should be able to get the version of any package with:
```
>>> from importlib.metadata import version
>>> version("cppimport")
'22.7.17.post1+g3d3de85.d20220802'
```

**Comment by bjornfor** [comment]
Thanks, that was quick! (And nice workaround, TIL.)

**Comment by tbenthompson** [comment]
I just pushed a release to pypi!
